### ISSUE TITLE
redis 

### ISSUE THREAD

**Issue by anthonymobile** [Bahus/easy_cache#7]
does the redis cache class work without a django installed and a CONFIG setup? i removed django from my env, and setup the cache with following per code example in README:

```
from redis import StrictRedis
from easy_cache.contrib.redis_cache import RedisCacheInstance
from easy_cache import caches

redis_cache = RedisCacheInstance(StrictRedis(host='127.0.0.1', port='6379'))
caches.set_default(redis_cache)
```

then calling the cache with a decorator:
```
@ecached('render_citywide_map_geojson', timeout=86400)
def render_citywide_map_geojson(reportcard_routes):
    etc...
```

yields an error after failing the django check at line 40 in core.py
`easy_cache.core.ImproperlyConfigured: Cache instance not found for alias "default-easy-cache"

did i miss something?

**Comment by Bahus** [comment]
Hi! Thank you for using the package!

It should work as expected, make sure that:

1. This code `caches.set_default(redis_cache)` executed before a module with `render_citywide_map_geojson` is imported.
2. If your application operates in multithreaded environment you should execute `caches.set_default(redis_cache)` in every thread.

If your application uses Flask and it runs with debug=True, then you get multithreading issue, which can be fixed with the following code:

```python
from redis import StrictRedis
from easy_cache.contrib.redis_cache import RedisCacheInstance
from easy_cache import caches

redis_cache = RedisCacheInstance(StrictRedis(host='127.0.0.1', port='6379'))
caches.set_default(redis_cache)

if app.debug:

    def set_cache_in_current_thread(*args, **kwargs):
        caches.set_default(redis_cache)

    admin_app.before_first_request(set_cache_in_current_thread)
```

Please try it and let me know the results.

**Comment by Bahus** [comment]
@anthonymobile hello, is there any news?

**Comment by anthonymobile** [comment]
it was the debugger! thanks very much.
